---
# config.yaml
# Please fill in these details for the database. 

# Default paths used by the application.
database_path: "./reconciliation.db"

# Donation account code prefixes are the Xero account codes to consider
# as donation accounts in queries relating to invoices and bank transactions.
donation_account_prefixes:
  - "41"
  - "42"
